name: Nifty50 VWAP Updater

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes
  workflow_dispatch:

jobs:
  update-nifty:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests pandas gspread gspread_dataframe oauth2client

      - name: Save service account JSON
        run: echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}" > service_account.json

      - name: Run Python script
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: python vwap_data.py
